package dev.ely.warptest

import android.app.Activity
import android.graphics.Color
import android.os.Bundle
import android.view.Gravity
import android.widget.TextView

/**
 * The test app Warp compiles on the phone.
 *
 * Deliberately references [R.string.app_name]. R is generated by aapt2 as
 * Java, compiled by javac, and only then can Kotlin see it — so if this
 * builds, the whole resource chain works.
 *
 * Uses the plain framework Activity rather than AppCompat: the point is to
 * test the toolchain, not to drag in dependency resolution.
 */
class MainActivity : Activity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val label = TextView(this).apply {
            text = getString(R.string.app_name) + "\n\nCompiled on the phone."
            textSize = 20f
            gravity = Gravity.CENTER
            setTextColor(Color.WHITE)
            setBackgroundColor(Color.parseColor("#101014"))
        }

        setContentView(label)
    }
}
